steps:
  #Execute SonarCloud Scan
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['verify', 'sonar:sonar','-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=rjdevsecops','-Dsonar.projectKey=rjdevsecops','-Dsonar.login=4c7b7c399407d75a6fe9e37d301f017f10d641af']